// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array        = require("bs-platform/lib/js/array.js");
var $$String       = require("bs-platform/lib/js/string.js");
var Caml_array     = require("bs-platform/lib/js/caml_array.js");
var Caml_format    = require("bs-platform/lib/js/caml_format.js");
var Readline$Day11 = require("../../util/readline.bs.js");

var arrayOfInts = /* array */[];

function mapToArray($$char) {
  var charString = $$String.make(1, $$char);
  var intFromChar = Caml_format.caml_int_of_string(charString);
  arrayOfInts.push(intFromChar);
  return /* () */0;
}

function handleInput(input) {
  $$String.iter(mapToArray, input);
  var halfArrayLength = (arrayOfInts.length >> 1);
  var firstHalf = $$Array.sub(arrayOfInts, 0, halfArrayLength);
  var secondHalf = $$Array.sub(arrayOfInts, halfArrayLength, halfArrayLength);
  var matching = $$Array.mapi((function (idx, item) {
          var match = +(item === Caml_array.caml_array_get(secondHalf, idx));
          if (match !== 0) {
            return (item << 1);
          } else {
            return 0;
          }
        }), firstHalf);
  console.log($$Array.fold_left((function (carry, value) {
              return carry + value | 0;
            }), 0, matching));
  return /* () */0;
}

Readline$Day11.question("What's the input?\n", handleInput);

exports.arrayOfInts = arrayOfInts;
exports.mapToArray  = mapToArray;
exports.handleInput = handleInput;
/*  Not a pure module */
