// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Readline$Day11 = require("./readline.bs.js");

Readline$Day11.question("What's the input?\n", (function (input) {
        console.log(input);
        return /* () */0;
      }));

/*  Not a pure module */
