// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");

var rl = Readline.createInterface({
      input: global.process.stdin,
      output: global.process.stdout,
      terminal: false
    });

function question(param, param$1) {
  rl.question(param, param$1);
  return /* () */0;
}

exports.rl       = rl;
exports.question = question;
/* rl Not a pure module */
