// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Readline$Day21 = require("../../util/src/readline.bs.js");

Readline$Day21.setPrompt("Input:");

Readline$Day21.prompt(/* () */0);

Readline$Day21.rl.on("line", (function (line) {
          if (line === "exit") {
            Readline$Day21.close(/* () */0);
          } else {
            console.log(line);
          }
          Readline$Day21.prompt(/* () */0);
          return /* () */0;
        })).on("close", (function () {
        console.log("Bye");
        global.process.exit(0);
        return /* () */0;
      }));

/*  Not a pure module */
